<?php

return [
    'brand' => 'SNS Furniture Manufacturing',
    'short_name' => 'SNS Furniture',
    'tagline' => 'Unleashing Potential, Embracing Self-Reliance',
    'about' => 'Manufacturer and retailer of high-quality household, office, and institutional furniture. Founded in 1992, SNS operates with 90+ professionals and a fully equipped plant 12 km east of Addis Ababa.',
    'phone' => '090 028 2029',
    'phone_href' => 'tel:+251900282029',
    'phones' => [
        '+251 118 931 113',
        '+251 143 960 070',
        '+251 143 960 071',
        '090 028 2029',
    ],
    'email' => 'snsfurnituremanufacture@gmail.com',
    'facebook' => 'https://www.facebook.com/SNSFurnitureOfficial',
    'google_reviews' => 'https://www.google.com/maps/search/?api=1&query=SNS+Furniture+Manufacturing+Addis+Ababa',
    'rating' => 3.8,
    'domain' => env('PUBLIC_SITE_DOMAIN', 'snsfurniture.et'),
    'hours' => [
        ['day' => 'Monday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Tuesday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Wednesday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Thursday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Friday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Saturday', 'hours' => '8:30 AM – 7:30 PM'],
        ['day' => 'Sunday', 'hours' => '12:00 PM – 7:30 PM'],
    ],
    'locations' => [
        [
            'name' => 'Kality Showroom',
            'address' => '3rd Floor, Kality Showroom Building, Addis Ababa',
            'map_query' => 'Kality Show Room Addis Ababa',
            'map_embed' => 'https://maps.google.com/maps?q=Kality%20Addis%20Ababa%20furniture&t=&z=14&ie=UTF8&iwloc=&output=embed',
        ],
        [
            'name' => 'Century Mall Showroom',
            'address' => 'Century Mall, Gurd Shola, Addis Ababa, Ethiopia',
            'map_query' => 'Century Mall Gurd Shola Addis Ababa',
            'map_embed' => 'https://maps.google.com/maps?q=Century%20Mall%20Gurd%20Shola%20Addis%20Ababa&t=&z=14&ie=UTF8&iwloc=&output=embed',
        ],
    ],
    'categories' => [
        'living-room' => 'Living room',
        'bedroom' => 'Bedroom',
        'office' => 'Office',
        'dining' => 'Dining',
        'outdoor' => 'Outdoor',
    ],
    'materials' => [
        'solid-wood' => 'Solid wood',
        'engineered-wood' => 'Engineered wood',
        'metal' => 'Metal',
        'upholstery' => 'Upholstery',
        'mixed' => 'Mixed materials',
    ],
    'products' => [
        [
            'slug' => 'addis-sofa-set',
            'name' => 'Addis Sofa Set',
            'category' => 'living-room',
            'room' => 'living-room',
            'material' => 'upholstery',
            'price' => 85000,
            'featured' => true,
            'short' => 'Three-seat sofa with matching chairs for modern living rooms.',
            'description' => 'A refined living-room set crafted for Ethiopian homes — deep cushions, durable frame, and fabric options suited to everyday comfort.',
            'dimensions' => 'Sofa 220 × 90 × 85 cm; chairs 80 × 80 × 85 cm',
            'materials_detail' => 'Hardwood frame, high-density foam, premium upholstery fabric',
            'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'nile-dining-table',
            'name' => 'Nile Dining Table',
            'category' => 'dining',
            'room' => 'dining',
            'material' => 'solid-wood',
            'price' => 62000,
            'featured' => true,
            'short' => 'Solid-wood dining table seating six with a warm walnut finish.',
            'description' => 'Manufactured in our workshops for lasting daily use. Smooth finish, sturdy legs, and generous surface for family meals.',
            'dimensions' => '180 × 90 × 75 cm',
            'materials_detail' => 'Solid hardwood, protective lacquer finish',
            'image' => 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1604578762246-41134aa37b0b?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'bole-king-bed',
            'name' => 'Bole King Bed',
            'category' => 'bedroom',
            'room' => 'bedroom',
            'material' => 'engineered-wood',
            'price' => 54000,
            'featured' => true,
            'short' => 'King-size bed with upholstered headboard and storage options.',
            'description' => 'A calm bedroom centerpiece with a padded headboard and durable platform construction.',
            'dimensions' => 'King 200 × 180 cm platform',
            'materials_detail' => 'Engineered wood structure, fabric headboard',
            'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
                'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'executive-office-desk',
            'name' => 'Executive Office Desk',
            'category' => 'office',
            'room' => 'office',
            'material' => 'mixed',
            'price' => 48000,
            'featured' => true,
            'short' => 'Spacious work desk with cable management and drawer unit.',
            'description' => 'Designed for productive offices — clean lines, durable surfaces, and storage for daily tools.',
            'dimensions' => '160 × 75 × 75 cm',
            'materials_detail' => 'Wood veneer top, metal frame, soft-close drawers',
            'image' => 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'mesa-coffee-table',
            'name' => 'Mesa Coffee Table',
            'category' => 'living-room',
            'room' => 'living-room',
            'material' => 'solid-wood',
            'price' => 18500,
            'featured' => false,
            'short' => 'Low coffee table with rounded edges and natural grain.',
            'description' => 'A versatile living-room accent piece that pairs with our sofa collections.',
            'dimensions' => '110 × 60 × 40 cm',
            'materials_detail' => 'Solid wood, matte finish',
            'image' => 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'akaki-wardrobe',
            'name' => 'Akaki Wardrobe',
            'category' => 'bedroom',
            'room' => 'bedroom',
            'material' => 'engineered-wood',
            'price' => 72000,
            'featured' => false,
            'short' => 'Three-door wardrobe with hanging rail and shelving.',
            'description' => 'Built for organized bedrooms with ample hanging space and adjustable shelves.',
            'dimensions' => '180 × 55 × 210 cm',
            'materials_detail' => 'Engineered wood, soft-close hinges',
            'image' => 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'terrace-lounge-chair',
            'name' => 'Terrace Lounge Chair',
            'category' => 'outdoor',
            'room' => 'outdoor',
            'material' => 'mixed',
            'price' => 22000,
            'featured' => false,
            'short' => 'Weather-ready lounge chair for balconies and terraces.',
            'description' => 'Comfortable outdoor seating with weather-resistant materials suitable for Addis climate.',
            'dimensions' => '70 × 75 × 80 cm',
            'materials_detail' => 'Powder-coated metal, outdoor fabric',
            'image' => 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
        [
            'slug' => 'sidist-kilo-bookshelf',
            'name' => 'Sidist Kilo Bookshelf',
            'category' => 'office',
            'room' => 'office',
            'material' => 'solid-wood',
            'price' => 31000,
            'featured' => false,
            'short' => 'Open bookshelf for offices and living spaces.',
            'description' => 'Tall open shelving for books, décor, and storage — manufactured for stability and clean display.',
            'dimensions' => '90 × 30 × 180 cm',
            'materials_detail' => 'Solid wood shelves and uprights',
            'image' => 'https://images.unsplash.com/photo-1594620302200-9a762185a3f8?auto=format&fit=crop&w=1200&q=80',
            'gallery' => [
                'https://images.unsplash.com/photo-1594620302200-9a762185a3f8?auto=format&fit=crop&w=1200&q=80',
            ],
        ],
    ],
];
